### ISSUE TITLE
Date Updated

### ISSUE THREAD

**Issue by i3luefire** [bradleysigma/tirules#20]
I think this is more of a feature request. And I am not sure if this is the best way to request a feature. 

The website says, "All information on this website is based off of v2.0 of the Living Rules Reference, released Nov 2020. This includes the Prophecy of Kings expansion.", which makes it seem like it was last updated before the codices, but it looks like some of the information might be newer than that.

Is it possible to add a last updated date, or something similar so that people can be more confident in how current the information is?

I apologize if this isn't the right place for this type request.

Also, amazing website!!! And, Thanks for all the hard work you do!!!

**Comment by Asrial** [comment]
I agree with this! It'd be great to have a "last updated" or maybe a version history.

Also agree about this being an amazing website!

**Comment by bradleysigma** [comment]
I've added a note about the Codices to the home page. I'm hesitant to add dates to the notes because some of the rules haven't changed since the game was released in 2017, and I don't want somebody seeing that and thinking "that ruling is seven years old, it might be out of date". Also, throwing dates on everything could make things look messy. In terms of a version history, there's the GitHub commit log.
